/********************************************************************
* ResultsDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error ResultsDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#include "G__ci.h"
extern "C" {
extern void G__cpp_setup_tagtableResultsDict();
extern void G__cpp_setup_inheritanceResultsDict();
extern void G__cpp_setup_typetableResultsDict();
extern void G__cpp_setup_memvarResultsDict();
extern void G__cpp_setup_globalResultsDict();
extern void G__cpp_setup_memfuncResultsDict();
extern void G__cpp_setup_funcResultsDict();
extern void G__set_cpp_environmentResultsDict();
}


#include "TROOT.h"
#include "TMemberInspector.h"
#include "Results.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__ResultsDictLN_TClass;
extern G__linked_taginfo G__ResultsDictLN_TBuffer;
extern G__linked_taginfo G__ResultsDictLN_TMemberInspector;
extern G__linked_taginfo G__ResultsDictLN_TObject;
extern G__linked_taginfo G__ResultsDictLN_vectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgR;
extern G__linked_taginfo G__ResultsDictLN_reverse_iteratorlEvectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__ResultsDictLN_Results;

/* STUB derived class for protected member access */
