{
    TTree* neut= (TTree*)f->Get("Neutron");
    int neutnum=neut->GetEntries();
    Int_t neuEventID;
    double neuInitTime;
    double neuInitKineE;
    double neuInitLocalX;
    double neuInitLocalY;
    double neuInitLocalZ;
    double neuInitLocalXCos;
    double neuInitLocalYCos;
    double neuInitLocalZCos;
    double neuCapLocalX;
    double neuCapLocalY;
    double neuCapLocalZ;
    int neuInitVolumeName;
    int neuCapVolumeName;
    double neuCapGammaESum;
    double neuCapTime;
    int neuCapTargetName;
    int neuOriginVolumeNumber;
    int neuMotherInteractionType;
    int    neuMotherFlukaNumber;
    neut->SetBranchAddress("EventID",&neuEventID);
    neut->SetBranchAddress("InitTime",&neuInitTime);
    neut->SetBranchAddress("InitKineE",&neuInitKineE);
    neut->SetBranchAddress("InitLocalX",&neuInitLocalX);
    neut->SetBranchAddress("InitLocalY",&neuInitLocalY);
    neut->SetBranchAddress("InitLocalZ",&neuInitLocalZ);
    neut->SetBranchAddress("InitLocalXCos",&neuInitLocalXCos);
    neut->SetBranchAddress("InitLocalYCos",&neuInitLocalYCos);
    neut->SetBranchAddress("InitLocalZCos",&neuInitLocalZCos);
    neut->SetBranchAddress("CapLocalX",&neuCapLocalX);
    neut->SetBranchAddress("CapLocalY",&neuCapLocalY);
    neut->SetBranchAddress("CapLocalZ",&neuCapLocalZ);
    neut->SetBranchAddress("InitVolumeName",&neuInitVolumeName);
    neut->SetBranchAddress("CapVolumeName",&neuCapVolumeName);
    neut->SetBranchAddress("CapGammaESum",&neuCapGammaESum);
    neut->SetBranchAddress("CapTime",&neuCapTime);
    neut->SetBranchAddress("CapTargetName",&neuCapTargetName);
    neut->SetBranchAddress("OriginVolumeNumber",&neuOriginVolumeNumber);
    neut->SetBranchAddress("MotherInteractionType",&neuMotherInteractionType);
    neut->SetBranchAddress("MotherFlukaNumber",&neuMotherFlukaNumber);
}
